---
- name: create directory
  file:
    path: "{{ app_path }}"
    state: directory
    mode: '2775'

- name: deploy application files
  copy:
    src: "{{ build_path }}"
    dest: "{{ app_path }}"
    mode: ug=rw,o=r,a+X
