---
- name: create directory
  file:
    path: "{{ app_path }}"
    state: directory
    mode: '2775'

- name: deploy application files
  ansible.posix.synchronize:
    src: "{{ build_path }}"
    dest: "{{ app_path }}"
    archive: true
    owner: false
    group: false
    rsync_opts:
      - "--chmod=Dug=rwx,Dg+s,Do=rx,Fug=rw,Fo=r"
