- name: create source path
  file:
    path: '{{ static_path }}'
    state: directory

- name: deploy toolinfo.json static files
  copy:
    src: "files/toolinfo.json"
    dest: "{{ static_path }}"
  loop:
    - 'toolinfo.json'

- name: Copy the webserver config
  copy:
    src: "files/lighttpd.conf"
    dest: "{{ base_path }}/.lighttpd.conf"

- name: stop the webserver
  command: webservice stop

- name: start the webserver
  command: webservice start

